# Task II: Classical GNNs #

Since I had so many problems with connecting the point cloud data into a graph, I tried a different approach. This method implements a CNN to classify Quark and Gluon jets.

This is one of my first data extraction methods when I was trying to understand the data format and representation. I didn't end up using it directly, but it helped me visualize the data storage structure.

In [2]:
import numpy as np

data = np.load('qg_dataset/QG_jets.npz', allow_pickle=True)
DATA_SIZE = 0
for key, value in data.items():
    print(key, value)
    DATA_SIZE = len(value)

X [[[ 2.68769142e-01  3.56903171e-01  4.74138734e+00  2.20000000e+01]
  [ 1.60076377e-01 -2.55609533e-01  4.55022910e+00  2.20000000e+01]
  [ 1.14868731e+00 -6.24380156e-02  4.50385377e+00 -2.11000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.21266321e+00 -1.12853089e-01  3.04708757e+00 -2.11000000e+02]
  [ 2.40893976e-01 -1.67174886e-02  2.82705667e+00  2.20000000e+01]
  [ 1.02778452e-01 -8.58720522e-02  3.04180579e+00  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 2.16829416e-01 -9.97057017e-01  5.32568913e-01  2.20000000e+01]
  [ 2.31359397e-01 -1.59192211e+00  2.02906587e-01  2.20000000e+01]
  [ 3.41572501e-01 -1.34588077

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch_geometric.data import Data, DataLoader
import numpy as np
import matplotlib as plt

The model uses 5 convolution layers with a ReLU activation function and a softmax at the end. 

In [4]:
class CustomNet(nn.Module):
    def __init__(self, input_channels=4):
        super(CustomNet, self).__init__()
        
        self.conv1 = nn.Conv1d(input_channels, 32, 1)
        self.conv2 = nn.Conv1d(32, 64, 1)
        self.conv3 = nn.Conv1d(64, 64, 1)
        self.conv4 = nn.Conv1d(64, 128, 1)
        self.conv5 = nn.Conv1d(128, 256, 1)
        
        self.fc1 = nn.Linear(256, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 2)
        
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.3)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.relu(self.conv2(x))
        x = self.relu(self.conv3(x))
        x = self.relu(self.conv4(x))
        x = self.relu(self.conv5(x))
        
        x = torch.max(x, 2, keepdim=True)[0]
        x = x.view(-1, 256)
        
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)
        x = self.softmax(x)
        
        return x

Originally, I had higher dimension arguments with two QG datasets (two .npz files), but the training was taking 10 minutes/epoch. I limited the dataset to one file, downscaled the network, increased the batch size, and decreased the number of epochs from the original parameters.


In [5]:
class JetDataset(torch.utils.data.Dataset):
    def __init__(self, data_path):
        self.data = np.load(data_path, allow_pickle=True)
        self.samples = []
        
        for key, value in self.data.items():
            if key == 'X':
                self.samples.extend([(sample, label) for sample, label in zip(value, self.data['y'])])
                
    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, idx):
        sample, label = self.samples[idx]
        sample = torch.tensor(sample.transpose(), dtype=torch.float32)
        label = torch.tensor(label, dtype=torch.long) 
        return sample, label

data_path = 'qg_dataset/QG_jets.npz'
jet_dataset = JetDataset(data_path)
batch_size = 128
data_loader = DataLoader(jet_dataset, batch_size=batch_size, shuffle=True)
train_loader = DataLoader(jet_dataset, batch_size=batch_size, shuffle=True)

c:\Users\realc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


This is the model initialization and training section. Again, I'm using Adam. The loss consistently decreases as the training continues.

In [8]:
model = CustomNet()
optimizer = optim.Adam(model.parameters(), lr=0.001)

criterion = nn.CrossEntropyLoss()

num_epochs = 10

for epoch in range(num_epochs):
    running_loss = 0.0
    for i, data in enumerate(data_loader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        
        outputs = model(inputs.float())
        loss = criterion(outputs, labels.long())
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        if i % 100 == 99:
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 100))
            running_loss = 0.0


[1,   100] loss: 0.635
[1,   200] loss: 0.599
[1,   300] loss: 0.584
[1,   400] loss: 0.576
[1,   500] loss: 0.580
[1,   600] loss: 0.572
[1,   700] loss: 0.571
[2,   100] loss: 0.562
[2,   200] loss: 0.569
[2,   300] loss: 0.565
[2,   400] loss: 0.561
[2,   500] loss: 0.566
[2,   600] loss: 0.564
[2,   700] loss: 0.566
[3,   100] loss: 0.563
[3,   200] loss: 0.561
[3,   300] loss: 0.557
[3,   400] loss: 0.558
[3,   500] loss: 0.562
[3,   600] loss: 0.560
[3,   700] loss: 0.567
[4,   100] loss: 0.557
[4,   200] loss: 0.554
[4,   300] loss: 0.561
[4,   400] loss: 0.560
[4,   500] loss: 0.564
[4,   600] loss: 0.560
[4,   700] loss: 0.559
[5,   100] loss: 0.562
[5,   200] loss: 0.553
[5,   300] loss: 0.555
[5,   400] loss: 0.553
[5,   500] loss: 0.551
[5,   600] loss: 0.552
[5,   700] loss: 0.552
[6,   100] loss: 0.557
[6,   200] loss: 0.552
[6,   300] loss: 0.557
[6,   400] loss: 0.552
[6,   500] loss: 0.549
[6,   600] loss: 0.552
[6,   700] loss: 0.558
[7,   100] loss: 0.549
[7,   200] 

#### Results ####

The loss throughout training went down from the initial 0.63 to 0.56 after 3 epochs, which is how much I originally ran it for. The accuracy for this was 73%. This is fine considering it only took a few minutes, but I thought a classification of 50/50 should do a little better. Also, the loss didn't stagger or start diverging from its trend, so I extended the number of epochs to 10. The final results with this change are 75% accuracy. The loss is still decreasing, but a more substantial change in the structure (like a working GNN) would likely to provide better classification for this problem.

In [9]:
def test(model, test_loader):
    correct = 0
    total = 0
    with torch.no_grad():
        for data in test_loader:
            inputs, labels = data
            outputs = model(inputs.float())
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    print('Accuracy on test set: %.2f %%' % accuracy)

test_loader = DataLoader(jet_dataset, batch_size=batch_size, shuffle=False)
test(model, test_loader)


Accuracy on test set: 75.78 %
